apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: utqpvu2ax-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/utqpvu2ax-java-quarkus-gitops